name: Daily Empty Commit

on:
  workflow_dispatch:

  schedule:
    - cron: "0 22 * * *" # JST 7:00 is UTC 22:00 of the previous day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create empty commit
        run: |
          git pull --rebase origin main || exit 1
          current_date=$(date '+%Y-%m-%d')
          git commit --allow-empty -m "Daily empty commit: ${current_date}"
          git push origin main || { echo "Failed to push changes"; exit 1; }
